# Generated by Django 4.1.2 on 2022-10-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
